name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Wait for MongoDB
      run: |
        echo "Waiting for MongoDB to be ready..."
        sleep 10

    - name: Create .env files for testing
      run: |
        # Tạo .env cho auth với MongoDB local
        cat > auth/.env << EOF
        MONGODB_AUTH_URI=mongodb://localhost:27017/auth_test
        JWT_SECRET=test-jwt-secret-for-ci-cd-pipeline-12345
        PORT=3000
        NODE_ENV=test
        EOF
        
        # Tạo .env cho product với MongoDB local
        cat > product/.env << EOF
        JWT_SECRET=test-jwt-secret-for-ci-cd-pipeline-12345
        MONGODB_PRODUCT_URI=mongodb://localhost:27017/product_test
        LOGIN_TEST_USER=test@example.com
        LOGIN_TEST_PASSWORD=testpassword123
        AUTH_SERVICE_URL=http://localhost:3000
        PORT=3001
        NODE_ENV=test
        EOF

    - name: Install dependencies with dev
      run: |
        echo "Installing dependencies including devDependencies..."
        # Sử dụng NODE_ENV=development để cài đặt cả devDependencies
        cd auth && NODE_ENV=development npm ci
        cd ../product && NODE_ENV=development npm ci
        
    - name: Run tests for auth service
      run: |
        echo "Running auth tests..."
        cd auth
        # Kiểm tra xem mocha có được cài đặt không
        ./node_modules/.bin/mocha --version || npx mocha --version
        npm test
        
    - name: Start auth service and run product tests
      run: |
        echo "Starting auth service and running product tests..."
        # Start auth service in background
        cd auth
        npm start &
        
        # Wait for auth service to be ready
        echo "Waiting for auth service to start..."
        sleep 25
        
        # Check if auth service is running với retry
        for i in {1..10}; do
          if curl -f http://localhost:3000/health || curl -f http://localhost:3000/login; then
            echo "✅ Auth service is ready!"
            break
          else
            echo "⏳ Attempt $i: Auth service not ready, waiting..."
            sleep 5
          fi
        done
        
        # Run product tests
        echo "Running product tests..."
        cd ../product
        npm test

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up..."
        pkill -f "node" || true