name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Check if secrets exist
      run: |
        echo "Checking secrets..."
        echo "MONGODB_PRODUCT_URI length: ${#MONGODB_PRODUCT_URI}"
        echo "JWT_SECRET length: ${#JWT_SECRET}"
        echo "LOGIN_TEST_USER length: ${#LOGIN_TEST_USER}"
        
        if [[ -z "$MONGODB_PRODUCT_URI" ]]; then
          echo "❌ ERROR: MONGODB_PRODUCT_URI secret is not set!"
          echo "Please go to Repository Settings → Secrets → Actions to add it"
          exit 1
        fi

    - name: Validate MongoDB URI format
      run: |
        echo "Checking MongoDB URI format..."
        URI="${{ secrets.MONGODB_PRODUCT_URI }}"
        echo "URI length: ${#URI}"
        
        if [[ -z "$URI" ]]; then
          echo "❌ ERROR: MONGODB_PRODUCT_URI is empty!"
          exit 1
        elif [[ $URI != mongodb://* && $URI != mongodb+srv://* ]]; then
          echo "❌ ERROR: MongoDB URI must start with 'mongodb://' or 'mongodb+srv://'"
          echo "Current URI starts with: ${URI:0:20}"
          exit 1
        else
          echo "✅ MongoDB URI format is correct"
          echo "URI starts with: ${URI:0:30}..."
        fi

    - name: Create .env files
      run: |
        # Tạo .env cho auth
        cat > auth/.env << EOF
        MONGODB_AUTH_URI=${{ secrets.MONGODB_PRODUCT_URI }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        PORT=3000
        EOF
        
        # Tạo .env cho product  
        cat > product/.env << EOF
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        MONGODB_PRODUCT_URI=${{ secrets.MONGODB_PRODUCT_URI }}
        LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}
        LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}
        AUTH_SERVICE_URL=http://localhost:3000
        PORT=3001
        EOF

    - name: Install dependencies
      run: |
        cd auth && npm ci
        cd ../product && npm ci
        
    - name: Run tests for auth
      run: |
        cd auth && npm test
        
    - name: Run tests for product
      run: |
        cd auth && npm start &
        sleep 25
        curl -f http://localhost:3000/health || echo "Auth service health check failed"
        cd product && npm test